### ISSUE TITLE
Change ruff configuration

### ISSUE THREAD

**Issue by pa-decarvalho** [pa-decarvalho/mkdocs-asciinema-player#40]
Example

ruff.toml
```toml
[lint]
select = ["ALL"]
ignore = ["D203", "D212"]
```

lint.yml (taskfile)
```
  ruff:
    desc: Run ruff
    cmds:
      - poetry run ruff check --config .config/ruff.toml
      - poetry run ruff format --config .config/ruff.toml
```
